exception handling

try{
    let a=prompt("enter any number")
    let t=parseInt(a)
    if(isNaN(t))
    {
        throw new error("invalid")
    }
    let h=t*2
    console.log(h)
}
catch(exception)
{
    console.error("An error occurred:", error.message);
} finally {
  // Code that will always run, regardless of whether there was an exception
  console.log("Execution completed.");

}


output
enter any number9
18
Execution completed.
